# K-Fold cross validation

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [17]:
digits=load_digits()

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
xtrain,xtest,ytrain,ytest=train_test_split(digits.data,digits.target,test_size=0.3)

In [20]:
lr=LogisticRegression()
lr.fit(xtrain,ytrain)
lr.score(xtest,ytest)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [21]:
svm=SVC()
svm.fit(xtrain,ytrain)
svm.score(xtest,ytest)

0.987037037037037

In [22]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)

0.9629629629629629

In [23]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [24]:
for train_i,test_i in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_i,test_i)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [25]:
def getscore(model,xt,xs,yt,ys):
    model.fit(xt,yt)
    return model.score(xs,ys)

In [26]:
getscore(LogisticRegression(),xtrain,xtest,ytrain,ytest)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [27]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)

In [29]:
scr_l=[]
scr_svm=[]
scr_rf=[]

for train_index,test_index in kf.split(digits.data):
    xtrain,xtest,ytrain,ytest=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    scr_l.append(getscore(LogisticRegression(),xtrain,xtest,ytrain,ytest))
    scr_svm.append(getscore(SVC(),xtrain,xtest,ytrain,ytest))
    scr_rf.append(getscore(RandomForestClassifier(n_estimators=40),xtrain,xtest,ytrain,ytest))

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refe

In [16]:
scr_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [17]:
scr_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [18]:
scr_rf

[0.9348914858096828, 0.9582637729549248, 0.9115191986644408]

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refe

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [21]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92777778, 0.9       , 0.95543175, 0.94707521, 0.93036212])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.92777778, 0.90277778, 0.94707521, 0.9637883 , 0.9275766 ])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=4),digits.data,digits.target)

array([0.8       , 0.78333333, 0.85236769, 0.88857939, 0.84401114])